package org.json_kula.jsonata_jvm;

import com.fasterxml.jackson.databind.JsonNode;
import org.json_kula.jsonata_jvm.runtime.RuntimeEvaluationException;

import java.util.concurrent.ConcurrentHashMap;

import static org.json_kula.jsonata_jvm.runtime.JsonataRuntime.*;

/**
 * Base class for all Java classes generated by the JSONata translator.
 *
 * <p>Provides the boilerplate that is identical across every generated class:
 * permanent-binding storage, the {@link #assign}/{@link #registerFunction} API,
 * and the evaluation scaffold (thread-local setup, exception mapping, teardown).
 *
 * <p>Subclasses must implement {@link #doEvaluate(JsonNode)}, which receives the
 * validated, non-null input document and returns the expression result.
 */
public abstract class AbstractJsonataExpression implements JsonataExpression {

    private final ConcurrentHashMap<String, JsonNode> __values = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, JsonataBoundFunction> __functions = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, org.joni.Regex> __regexes = new ConcurrentHashMap<>();
    private volatile int __timeoutMs = 0;

    @Override
    public void setTimeout(int timeoutMs) {
        __timeoutMs = timeoutMs;
    }

    @Override
    public void assign(String name, JsonNode value) {
        __values.put(name, value);
    }

    @Override
    public void registerFunction(String name, JsonataBoundFunction fn) {
        __functions.put(name, fn);
    }

    @Override
    public JsonNode evaluate(JsonNode input) throws JsonataEvaluationException {
        return evaluate(input, null);
    }

    @Override
    public final JsonNode evaluate(JsonNode __input, JsonataBindings __perEval)
            throws JsonataEvaluationException {
        beginEvaluation(__values, __functions, __perEval, __regexes, __timeoutMs);
        try {
            if (__input == null)
                throw new JsonataEvaluationException(null, "Input JSON cannot be null");
            return doEvaluate(__input);
        } catch (JsonataEvaluationException __e) {
            throw __e;
        } catch (RuntimeEvaluationException __e) {
            throw new JsonataEvaluationException(__e.getErrorCode(), __e.getMessage(), __e);
        } catch (Exception __e) {
            throw new JsonataEvaluationException(null, __e.getMessage(), __e);
        } finally {
            endEvaluation();
        }
    }

    /**
     * Evaluates this expression with {@code scope} installed, so that every lambda it creates is
     * minted into that durable scope instead of the per-evaluation map and stays callable
     * afterwards. Used exactly once per {@link JsonataFunctionLibrary}, on its definition
     * expression.
     *
     * @param input    the input document the definition expression is evaluated against
     * @param bindings definition-time bindings, or {@code null}
     * @param scope    the durable lambda scope to mint into
     * @return the raw expression result — for a rewritten definition expression, the export object
     */
    final JsonNode evaluateDefining(JsonNode input, JsonataBindings bindings,
                                    org.json_kula.jsonata_jvm.runtime.LambdaScope scope)
            throws JsonataEvaluationException {
        beginEvaluation(__values, __functions, bindings, __regexes, __timeoutMs, scope);
        try {
            if (input == null)
                throw new JsonataEvaluationException(null, "Input JSON cannot be null");
            return doEvaluate(input);
        } catch (JsonataEvaluationException __e) {
            throw __e;
        } catch (RuntimeEvaluationException __e) {
            throw new JsonataEvaluationException(__e.getErrorCode(), __e.getMessage(), __e);
        } catch (Exception __e) {
            throw new JsonataEvaluationException(null, __e.getMessage(), __e);
        } finally {
            endEvaluation();
        }
    }

    /** Permanent value bindings registered on this instance — read by exported library functions. */
    final ConcurrentHashMap<String, JsonNode> permanentValues() {
        return __values;
    }

    /** Permanent function bindings registered on this instance. */
    final ConcurrentHashMap<String, JsonataBoundFunction> permanentFunctions() {
        return __functions;
    }

    /** This instance's regex cache, reused when an exported function opens its own frame. */
    final ConcurrentHashMap<String, org.joni.Regex> instanceRegexes() {
        return __regexes;
    }

    /**
     * Evaluates the compiled JSONata expression against the given input document.
     *
     * @param __root the validated, non-null input document
     * @return the expression result ({@code MissingNode} for undefined, never Java {@code null})
     * @throws Exception any runtime error; the caller maps it to {@link JsonataEvaluationException}
     */
    protected abstract JsonNode doEvaluate(JsonNode __root) throws Exception;
}
