package org.json_kula.jsonata_jvm;

import com.fasterxml.jackson.databind.JsonNode;
import org.json_kula.jsonata_jvm.runtime.RuntimeEvaluationException;

import java.util.concurrent.ConcurrentHashMap;

import static org.json_kula.jsonata_jvm.runtime.JsonataRuntime.*;

/**
 * Base class for all Java classes generated by the JSONata translator.
 *
 * <p>Provides the boilerplate that is identical across every generated class:
 * permanent-binding storage, the {@link #assign}/{@link #registerFunction} API,
 * and the evaluation scaffold (thread-local setup, exception mapping, teardown).
 *
 * <p>Subclasses must implement {@link #doEvaluate(JsonNode)}, which receives the
 * validated, non-null input document and returns the expression result.
 */
public abstract class AbstractJsonataExpression implements JsonataExpression {

    private final ConcurrentHashMap<String, JsonNode> __values = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, JsonataBoundFunction> __functions = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, org.joni.Regex> __regexes = new ConcurrentHashMap<>();
    private volatile int __timeoutMs = 0;

    /**
     * The permanent bindings, pre-merged into the form the evaluation frame installs. Rebuilt
     * lazily after {@link #assign} or {@link #registerFunction} rather than on every evaluation —
     * merging per call dominated the cost of a small expression.
     */
    private volatile JsonataBindings __permanent = new JsonataBindings();

    /**
     * The {@code $eval} delegate of the factory that compiled this instance. Held per instance so
     * that constructing another factory cannot change how this expression evaluates {@code $eval}.
     */
    private volatile org.json_kula.jsonata_jvm.runtime.JsonataRuntime.EvalDelegate __evalDelegate;

    @Override
    public void setTimeout(int timeoutMs) {
        __timeoutMs = timeoutMs;
        if (timeoutMs > 0) org.json_kula.jsonata_jvm.runtime.JsonataRuntime.notifyTimeoutInUse();
    }

    @Override
    public void assign(String name, JsonNode value) {
        __values.put(name, value);
        __permanent = null;
    }

    @Override
    public void registerFunction(String name, JsonataBoundFunction fn) {
        __functions.put(name, fn);
        __permanent = null;
    }

    /**
     * Returns the permanent bindings as one object, rebuilding it only after a change. Racing
     * callers may each build one; they are equivalent, so the last writer wins harmlessly.
     */
    private JsonataBindings permanentBindings() {
        JsonataBindings cached = __permanent;
        if (cached == null) {
            cached = new JsonataBindings();
            __values.forEach(cached::bindValue);
            __functions.forEach(cached::bindFunction);
            __permanent = cached;
        }
        return cached;
    }

    @Override
    public JsonNode evaluate(JsonNode input) throws JsonataEvaluationException {
        return evaluate(input, null);
    }

    @Override
    public final JsonNode evaluate(JsonNode __input, JsonataBindings __perEval)
            throws JsonataEvaluationException {
        beginEvaluation(permanentBindings(), __perEval, __regexes, __timeoutMs, __evalDelegate);
        try {
            if (__input == null)
                throw new JsonataEvaluationException(null, "Input JSON cannot be null");
            return doEvaluate(__input);
        } catch (JsonataEvaluationException __e) {
            throw __e;
        } catch (RuntimeEvaluationException __e) {
            throw new JsonataEvaluationException(__e.getErrorCode(), __e.getMessage(), __e);
        } catch (Exception __e) {
            throw new JsonataEvaluationException(null, __e.getMessage(), __e);
        } finally {
            endEvaluation();
        }
    }

    /** Set by the factory that compiled this instance. */
    final void setEvalDelegate(org.json_kula.jsonata_jvm.runtime.JsonataRuntime.EvalDelegate delegate) {
        this.__evalDelegate = delegate;
    }

    /** The permanent bindings of this instance — read by exported library functions. */
    final JsonataBindings permanentBindingSet() {
        return permanentBindings();
    }

    /** This instance's regex cache, reused when an exported function opens its own frame. */
    final ConcurrentHashMap<String, org.joni.Regex> instanceRegexes() {
        return __regexes;
    }

    /**
     * Evaluates the compiled JSONata expression against the given input document.
     *
     * @param __root the validated, non-null input document
     * @return the expression result ({@code MissingNode} for undefined, never Java {@code null});
     *         returned to the caller as-is
     * @throws Exception any runtime error; the caller maps it to {@link JsonataEvaluationException}
     */
    protected abstract JsonNode doEvaluate(JsonNode __root) throws Exception;
}
