package org.json_kula.jsonata_jvm;

import com.fasterxml.jackson.databind.JsonNode;
import org.json_kula.jsonata_jvm.runtime.RuntimeEvaluationException;

import java.util.concurrent.ConcurrentHashMap;

import static org.json_kula.jsonata_jvm.runtime.JsonataRuntime.*;

/**
 * Base class for all Java classes generated by the JSONata translator.
 *
 * <p>Provides the boilerplate that is identical across every generated class:
 * permanent-binding storage, the {@link #assign}/{@link #registerFunction} API,
 * and the evaluation scaffold (thread-local setup, exception mapping, teardown).
 *
 * <p>Subclasses must implement {@link #doEvaluate(JsonNode)}, which receives the
 * validated, non-null input document and returns the expression result.
 */
public abstract class AbstractJsonataExpression implements JsonataExpression {

    private final ConcurrentHashMap<String, JsonNode> __values = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, JsonataBoundFunction> __functions = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, org.joni.Regex> __regexes = new ConcurrentHashMap<>();

    @Override
    public void assign(String name, JsonNode value) {
        __values.put(name, value);
    }

    @Override
    public void registerFunction(String name, JsonataBoundFunction fn) {
        __functions.put(name, fn);
    }

    @Override
    public JsonNode evaluate(JsonNode input) throws JsonataEvaluationException {
        return evaluate(input, null);
    }

    @Override
    public final JsonNode evaluate(JsonNode __input, JsonataBindings __perEval)
            throws JsonataEvaluationException {
        beginEvaluation(__values, __functions, __perEval, __regexes);
        try {
            if (__input == null)
                throw new JsonataEvaluationException(null, "Input JSON cannot be null");
            return doEvaluate(__input);
        } catch (JsonataEvaluationException __e) {
            throw __e;
        } catch (RuntimeEvaluationException __e) {
            throw new JsonataEvaluationException(__e.getErrorCode(), __e.getMessage(), __e);
        } catch (Exception __e) {
            throw new JsonataEvaluationException(null, __e.getMessage(), __e);
        } finally {
            endEvaluation();
        }
    }

    /**
     * Evaluates the compiled JSONata expression against the given input document.
     *
     * @param __root the validated, non-null input document
     * @return the expression result ({@code MissingNode} for undefined, never Java {@code null})
     * @throws Exception any runtime error; the caller maps it to {@link JsonataEvaluationException}
     */
    protected abstract JsonNode doEvaluate(JsonNode __root) throws Exception;
}
