package org.json_kula.jsonata_jvm;

import com.fasterxml.jackson.databind.JsonNode;
import org.json_kula.jsonata_jvm.translator.Translator;

/**
 * Common contract for all Java classes generated by the JSONata translator.
 *
 * <p>Each generated class represents a compiled JSONata expression and implements
 * this interface so that callers can evaluate expressions uniformly without
 * knowing which specific expression was compiled.
 *
 * <p>Usage:
 * <pre>{@code
 * JsonataExpression expr = new CompiledSumExpression();
 * JsonNode result = expr.evaluate("{\"orders\": [{\"price\": 10}, {\"price\": 20}]}");
 * }</pre>
 */
public interface JsonataExpression {

    /**
     * Evaluates this JSONata expression against the given JSON input.
     *
     * @param json the input JSON document as a string
     * @return the result of the expression, or {@code NullNode} if the expression
     *         yields no match (consistent with JSONata's undefined-to-null semantics)
     * @throws JsonataEvaluationException if the input is not valid JSON or the
     *         expression cannot be applied to the given input
     */
    JsonNode evaluate(String json) throws JsonataEvaluationException;

    /**
     * Returns the original JSONata expression string that was compiled into this
     * instance.
     *
     * <p>Classes generated by {@link Translator} override this
     * method to return the exact source text passed at translation time.
     * Manually written implementations may return an empty string.
     *
     * @return the JSONata source expression, or {@code ""} if not available
     */
    default String getSourceJsonata() {
        return "";
    }
}
