package org.json_kula.jsonata_jvm;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.json_kula.jsonata_jvm.translator.Translator;

/**
 * Common contract for all Java classes generated by the JSONata translator.
 *
 * <p>Each generated class represents a compiled JSONata expression and implements
 * this interface so that callers can evaluate expressions uniformly without
 * knowing which specific expression was compiled.
 *
 * <p>Usage:
 * <pre>{@code
 * JsonataExpression expr = new CompiledSumExpression();
 * JsonNode result = expr.evaluate(objectMapper.readTree("{\"orders\": [{\"price\": 10}, {\"price\": 20}]}"));
 * }</pre>
 *
 * <h2>Bindings</h2>
 * <p>External values and Java functions can be injected into the expression:
 * <ul>
 *   <li>Per-evaluation: pass a {@link JsonataBindings} instance to
 *       {@link #evaluate(JsonNode, JsonataBindings)}.</li>
 *   <li>Permanent (for the lifetime of this instance): call
 *       {@link #assign(String, JsonNode)} or
 *       {@link #registerFunction(String, JsonataBoundFunction)}.</li>
 * </ul>
 * Either way, {@link #useLibrary(JsonataLibrary)} and {@link JsonataBindings#useLibrary} apply
 * everything a {@link JsonataLibrary} exports in one call.
 * <p>
 * Permanent bindings are merged with per-evaluation bindings at call time;
 * per-evaluation values take precedence when both define the same name.
 */
public interface JsonataExpression {

    /**
     * Evaluates this JSONata expression against the given JSON input with no
     * additional bindings beyond the permanent ones already registered on this
     * instance.
     *
     * @param input the input JSON document as a JsonNode
     * @return the result of the expression, or {@link com.fasterxml.jackson.databind.node.MissingNode}
     *         if it yields no match — JSONata's <em>undefined</em>. Test for it with
     *         {@code result.isMissingNode()}; note that {@code isNull()} is {@code false} for it,
     *         since JSONata distinguishes an absent value from an explicit {@code null}.
     * @throws JsonataEvaluationException if the expression cannot be applied to the given input
     */
    JsonNode evaluate(JsonNode input) throws JsonataEvaluationException;

    /**
     * Evaluates this JSONata expression against the given JSON input, making
     * the supplied per-evaluation bindings available as {@code $name} references
     * inside the expression.
     *
     * <p>Per-evaluation bindings are merged with any permanent bindings already
     * registered via {@link #assign} / {@link #registerFunction}; per-evaluation
     * values win when both define the same name.
     *
     * @param input    the input JSON document as a JsonNode
     * @param bindings per-evaluation named values and functions, or {@code null}
     *                 to use only permanent bindings
     * @return the result of the expression, or {@code MissingNode} if it yields no match
     * @throws JsonataEvaluationException if the expression cannot be applied to the given input
     */
    default JsonNode evaluate(JsonNode input, JsonataBindings bindings) throws JsonataEvaluationException {
        // Silently dropping the bindings would make a hand-written implementation look like it
        // supported them. Classes generated by this library override this method.
        if (bindings != null && !bindings.isEmpty()) {
            throw new UnsupportedOperationException(
                    getClass().getName() + " does not support per-evaluation bindings");
        }
        return evaluate(input);
    }

    /**
     * Permanently binds {@code value} to {@code name} for all future evaluations
     * of this instance.
     *
     * <p>The value is accessible inside the expression as {@code $name}.
     *
     * @param name  the variable name (without the leading {@code $})
     * @param value the immutable {@link JsonNode} to bind
     */
    default void assign(String name, JsonNode value) {}

    /**
     * Permanently registers a Java function under {@code name} for all future
     * evaluations of this instance.
     *
     * <p>The function is callable inside the expression as {@code $name(args...)}.
     *
     * @param name the function name (without the leading {@code $})
     * @param fnc  the {@link JsonataBoundFunction} implementation
     */
    default void registerFunction(String name, JsonataBoundFunction fnc) {}

    /**
     * Permanently binds everything {@code library} exports — its functions as function bindings, its
     * constants as value bindings — for all future evaluations of this instance.
     *
     * <p>The permanent counterpart of {@link JsonataBindings#useLibrary}, and equivalent to applying
     * both maps by hand:
     *
     * <pre>{@code
     * library.getFunctions().forEach(expr::registerFunction);
     * library.getConstants().forEach(expr::assign);
     * }</pre>
     *
     * <p>Which of the two a name belongs to is the library's business — the definition decides it by
     * what each name evaluates to — so taking both together is almost always what a caller wants.
     * Applying two libraries that export the same name leaves the later call's binding in place, as
     * re-binding a name always does; a per-evaluation binding still wins over anything registered
     * here.
     *
     * @param library the library to apply; its exports are copied, so later changes to it — short of
     *                {@link JsonataLibrary#close()} — do not affect this instance
     */
    default void useLibrary(JsonataLibrary library) {
        library.getFunctions().forEach(this::registerFunction);
        library.getConstants().forEach(this::assign);
    }

    /**
     * Sets a wall-clock timeout for all future evaluations on this instance.
     * If an evaluation exceeds {@code timeoutMs} milliseconds it is interrupted
     * and a {@link JsonataEvaluationException} with code {@code U1001} is thrown.
     * Pass {@code 0} or a negative value to disable the timeout (default).
     */
    default void setTimeout(int timeoutMs) {}

    /**
     * Returns the original JSONata expression string that was compiled into this
     * instance.
     *
     * <p>Classes generated by {@link Translator} override this
     * method to return the exact source text passed at translation time.
     * Manually written implementations may return an empty string.
     *
     * @return the JSONata source expression, or {@code ""} if not available
     */
    default String getSourceJsonata() {
        return "";
    }
}
